
baseURL = 'https://deadtechguy.fun/'
languageCode = 'en-us'
title = 'Dead Tech Guy'
theme = "hugo-theme-latte"

[params]
user = "hungry"
hostname = "deadtechguy.fun"
displayDateFormat = "02.01.2006"



footerHtml = """
<a href="https://x.com/dtg_fun" class="footerLink" target="_blank">X / Twitter</a>
&nbsp;|&nbsp;
<a href="https://www.youtube.com/@DeadTechGuy" class="footerLink" target="_blank">YouTube</a>
"""







  [params.author]
    name = "Dead Tech Guy"
    email = "hugo@example.com"
    avatarFirst = false



# ---------- MENU AT TOP RIGHT ----------
[menu]
  [[menu.header]]
    name = "about"
    url = "/about/"
    weight = 0

  [[menu.header]]
    name = "blog"
    url = "/posts/"
    weight = 1

  [[menu.header]]
    name = "contact"
    url = "/contact/"
    weight = 2

# (Add/remove as you need)

[[params.social]]
key = 0
name = "TechReviews"
url = "/tech-reviews/"

[[params.social]]
key = 1
name = "Tech Blog"
url = "/tech-blog/"

[[params.social]]
key = 2
name = "Personal"
url = "/personal/"








[caches]
  [caches.images]
    dir = ':cacheDir/images'
